name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      verify-env:
        description: "If you really want to push to production, write 'production'."
        required: true

jobs:
  environment_check:
    runs-on: ubuntu-latest
    steps:
      - name: Display Failure Message
        if: |
          github.event.inputs.verify-env != 'production' ||
          github.ref != 'refs/heads/main'
        run: |
          echo "This workflow is not applicable for this branch."
          echo "Input parameter is ${{ github.event.inputs.verify-env }}"
          echo "Branch name is ${{ github.ref }}"

  production_deploy:
    if: |
      github.event.inputs.verify-env == 'production' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 git.wpengine.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "Host git.wpengine.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  Hostname git.wpengine.com" >> ~/.ssh/config
          echo "  PreferredAuthentications publickey" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config

      - name: Push to Another Repo
        run: |
          git remote add wpengine/production "${{ vars.WPE_PRODUCTION }}"
          git push -v -o remove-empty-dirs wpengine/production main
